version: "1.0"

services:

  yolov8:
    container_name: yolov8
    image: yolov8_image
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /workdir/share:/share
    working_dir: /share
    command: bash /share/yolov8_run.sh
    restart: unless-stopped

  goke7605:
    container_name: goke7605
    image: ubuntu18.04_xmtvm:AI_TOOLCHAIN_V020_V3010_145_20250827
    volumes:
      - /workdir/share:/share
    working_dir: /share
    command: bash /share/goke_run.sh
    restart: unless-stopped